/*
HOP TEAM EXPLORATORY ANALYSIS

QUESTIONS:
- TAXONOMY SWITCH VALUES
- HOSPITAL RECEIVING PROVIDERS

NOTES:
- NPPES POSTAL CODE DOES NOT DIRECTLY MATCH THE ZIP_CBSA ZIP
- NPPES TAXONOMY SWITCH VALUES CAN BE 'Y', 'N', 'X', AND NULL
*/

SELECT *
FROM NPPES
WHERE ADDRESS_STATE_NAME IN ('TENNESSEE', 'TN')
ORDER BY ADDRESS_POSTAL_CODE;

SELECT *
FROM HOP_TEAM
LIMIT 5;

SELECT *
FROM NUCC
LIMIT 5;

SELECT *
FROM ZIP_CBSA
WHERE USPS_ZIP_PREF_STATE = 'TN'
ORDER BY ZIP;


-- PCP specialties for referring providers
-- For the referring providers, filter to Primary Care Physicians (PCPs) only: 
-- You can look for classifications of "Family Medicine", "Internal Medicine", "Pediatrics", and "General Practice"

/* TESTS */

SELECT
	CODE,
	CLASSIFICATION,
	SPECIALIZATION,
	DISPLAY_NAME
FROM NUCC
WHERE CLASSIFICATION ILIKE ANY(ARRAY[
	'FAMILY MEDICINE',
	'INTERNAL MEDICINE',
	'PEDIATRICS',
	'GENERAL PRACTICE'
]);	-- 68 ROWS

SELECT DISTINCT HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_1
FROM NPPES;	-- DISTINCT SWITCH VALUES: 'Y', 'N', 'X', NULL

-- SELECT COLUMN_NAME
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'nppes'
-- 	AND COLUMN_NAME LIKE 'healthcare_primary_taxonomy_switch%'

-- CREATE A VIEW WITH THIS QUERY: TN_PCPS
WITH 
	PCP_CLASSIFICATIONS AS (
		SELECT
			CODE,
			CLASSIFICATION
		FROM NUCC
		WHERE CLASSIFICATION ILIKE ANY(ARRAY[
			'FAMILY MEDICINE',
			'INTERNAL MEDICINE',
			'PEDIATRICS',
			'GENERAL PRACTICE'
		])
	),
	TN_NPPES_PRIMARY_TAXONOMY_CODES AS (
		SELECT
			NPI,
			CASE
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_1 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_1
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_2 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_2
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_3 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_3
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_4 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_4
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_5 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_5
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_6 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_6
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_7 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_7
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_8 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_8
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_9 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_9
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_10 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_10
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_11 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_11
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_12 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_12
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_13 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_13
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_14 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_14
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_15 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_15
				ELSE NULL
			END AS HEALTHCARE_PRIMARY_TAXONOMY_CODE
		FROM NPPES
		WHERE ADDRESS_STATE_NAME IN ('TENNESSEE', 'TN')
	)
SELECT
	N.NPI,
	N.ORGANIZATION_NAME,
	N.FIRST_NAME || ' ' || N.LAST_NAME AS pcp,
	T.HEALTHCARE_PRIMARY_TAXONOMY_CODE,
	C.CLASSIFICATION
FROM NPPES N
	INNER JOIN TN_NPPES_PRIMARY_TAXONOMY_CODES T USING (NPI)
	INNER JOIN PCP_CLASSIFICATIONS C ON T.HEALTHCARE_PRIMARY_TAXONOMY_CODE = C.CODE
ORDER BY N.NPI;	-- 13100 ROWS


-- Hospitals for receiving providers
-- For the receiving providers, filter to hospitals.

/* TESTS */
SELECT *
FROM NUCC
WHERE GROUPING ILIKE '%HOSPITAL%'
	OR CLASSIFICATION ILIKE '%HOSPITAL%'; -- 24 ROWS

-- CREATE A VIEW WITH THIS QUERY: TN_HOSPITALS
WITH 
	HOSPITAL_CLASSIFICATIONS AS (
		SELECT
			CODE,
			CLASSIFICATION
		FROM NUCC
		WHERE GROUPING ILIKE '%HOSPITAL%'
			OR CLASSIFICATION ILIKE '%HOSPITAL%'
	),
	TN_NPPES_PRIMARY_TAXONOMY_CODES AS (
		SELECT
			NPI,
			CASE
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_1 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_1
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_2 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_2
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_3 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_3
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_4 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_4
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_5 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_5
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_6 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_6
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_7 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_7
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_8 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_8
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_9 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_9
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_10 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_10
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_11 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_11
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_12 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_12
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_13 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_13
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_14 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_14
				WHEN HEALTHCARE_PRIMARY_TAXONOMY_SWITCH_15 = 'Y' THEN HEALTHCARE_TAXONOMY_CODE_15
				ELSE NULL
			END AS HEALTHCARE_PRIMARY_TAXONOMY_CODE
		FROM NPPES
		WHERE ADDRESS_STATE_NAME IN ('TENNESSEE', 'TN')
	)
SELECT
	N.NPI,
	N.ORGANIZATION_NAME,
	N.FIRST_NAME || ' ' || N.LAST_NAME AS pcp,
	T.HEALTHCARE_PRIMARY_TAXONOMY_CODE,
	C.CLASSIFICATION
FROM NPPES N
	INNER JOIN TN_NPPES_PRIMARY_TAXONOMY_CODES T USING (NPI)
	INNER JOIN HOSPITAL_CLASSIFICATIONS C ON T.HEALTHCARE_PRIMARY_TAXONOMY_CODE = C.CODE
ORDER BY N.NPI; -- 1124 ROWS


-- Identify PCPs who refer patients and the distribution of their referrals across major hospitals.
-- Find PCPs who refer few or no patients to Vanderbilt but send patients to competitor hospitals.
-- Aggregate by PCP specialty to understand which specialties are underrepresented in Vanderbilt’s referral network.